### ISSUE TITLE
Persistence failing with Vanilla BIS Assets

### ISSUE THREAD

**Issue by armatourist** [ostinelli/SCAR_UCM#13]
Hi Boss, 

sorry to report that construction work on Stratis is not going as planned... 

Could you be so kind to check my test mission for any user errors with the ALIVE modules?  To save time, I have taken the ALIVE Demo mission and stripped out all the extra scripts from Hazey and put AIS Revive in so we can see if UCM works if just this script is active  For me, there was no difference between AIS active and not active.  In both cases UCM loading failed.  

After sucessfully (as in: does it work while actually INGAME?) testing the code you have given to me for checking if a construction is complete, I have made an ALIVE+UCM test mission using ONLY vanilla BIS assets on Stratis with three different construction sites.  In the long run, I want to have UCM in a mission with lots of addons and various scripts on Kunduz, but ofc I won't bother you with that before I get UCM to run in a no mods environment first.  

As mentioned on top, my test mission has just one script active; the AIS Revive Script. All other scripts are not active ATM and also no mods. The three construction sites all get completed just fine ingame, and the saving seems to work, too.  I press ESC, then do the UCM save and then an ALIVE SP save.  

Upon loading the game, the usual ALIVE persistence indicators like SITREPS, player position and equipment do work just fine.  But the constructed assets are gone - while the workers and the foreman still tell me "construction complete"! 

Here's the mission: 

https://www.dropbox.com/s/zsu179t01chlor8/ALIVE_TEST_STRATIS_UCM_BAREBONE_0.Stratis.pbo.7z?dl=0 

and here the .rpt claiming a UCM persistence module couldn't be found - but it's placed! 

https://www.dropbox.com/s/w11l9iw2lht4zbc/tourists_tests_persistence_fail_1.7z?dl=0 

Hope you have an idea where i screwed up... 

Best Regards & THX in advance for your support

tourist

**Comment by ostinelli** [comment]
Sorry tourist, I do not have time to check custom made missions. All instructions are on the page and you do have a working example mission you can start from available for download. :)

Thank you for trying this, keep tight!
