### ISSUE TITLE
Foreman Functions Disappear

### ISSUE THREAD

**Issue by Ezaco** [ostinelli/SCAR_UCM#15]
Had 40 pieces set to work at 5 minutes each when 10 workers are present. Left the server for a bit because I had to go to dinner.. when I came back ~1.5 hours later, I had completely lost the ability to interact with anything. Couldn't use the foreman functions, and couldn't load one of my materials. For testing purposes I restarted the mission, and all the functionality came back. I left the server and rejoined, and I could still call materials but could no longer call for workers.
 
Also had another player JIP and they could call for materials, but not for workers.

Confirmed this happens whether the foreman is set as a vehicle (first test) or an AI (second test, to make sure it wasn't just an issue with setting it as anything but an AI).

Steps to reproduce:

1. Create mission
2. Upload and launch mission on dedicated server
3. Check foreman for command abilities.
4. Disconnect from server and rejoin.
5. Check foreman for command abilities. Request to call workers has disappeared.
6. (Alternative) Leave mission running for 1-2 hours, then rejoin server. Ability to use any UCM commands has disappeared.

**Comment by ostinelli** [comment]
The actions are added with [remoteExec](https://community.bistudio.com/wiki/remoteExec) in [this file](https://github.com/ostinelli/SCAR_UCM/blob/master/functions/actions/fn_addActionsToForeman.sqf).

My understanding of this function is that it will be run for every JIP, hence the commands should be attached to JIP.

I will perform some additional testing, but if you have insights do share.

**Comment by ostinelli** [comment]
6e8957b1876aeaff8de51bbbcf48bd4c2a7a6df0 should fix it. I will provide a build tonight, let me know if this solves it for you.

**Comment by ostinelli** [comment]
No follow up, closing. Reopen if you encounter the same error, thanks.
