### ISSUE TITLE
Add ALiVE integration & persistence

### ISSUE THREAD

**Issue by ostinelli** [ostinelli/SCAR_UCM#2]
Discussions here:

- persistence: http://alivemod.com/forum/3168-get-save-data-from-cloud
- integration http://alivemod.com/forum/3162-alive-and-ucm

**Comment by HeroesandvillainsOS** [comment]
Commenting so I'll get notified as to how this progresses. :)

**Comment by ostinelli** [comment]
You can just click on Subscribe here to the right now, no need to comment :) Just FYI, but good seeing you here too.

**Comment by ostinelli** [comment]
Having issues in persistence, added discussion in first post.

**Comment by ostinelli** [comment]
UCM is now integrated with ALiVE, with some caveats. Here are the details of it.

**ALiVE objectives**

The Construction Area is automatically added as a Custom Objective to the hostile OPCOMs. This objective is also moved when the construction moves.

**ALiVE profiles**

The workers are not profiled by ALiVE Virtual_AI_System, and therefore they will not be attacked by profiled enemies when they are virtualized. This substantially means that at least one player needs to be next to the workers, which will cause ALiVE profiled enemies to be spawned on the map and hence attack the workers.

**ALiVE Persistence**

Whan ALiVE saves its data, it will trigger an endMission. UCM listens for that event and automatically uses its Persistent Module to save its data. Therefore, if you want UCM data to be also saved when you save ALiVE, the only thing you have to do is to drop the UCM Persistent Module in your mission.

Note that UCM data will be saved locally, regardless of the ALiVE Data setting.
