### ISSUE TITLE
Add ability to create/designate workers & materials in-editor

### ISSUE THREAD

**Issue by Nels0** [ostinelli/SCAR_UCM#3]
I'm a part of a milsim community and it wouldn't really fly _(get it)_ to have supplies and workers have to be spawned/flown in by AI.

I had a brief look through the functions - and it does look like I could spawn workers using `createWorkers`, but it would be easier to have a `designateWorkers` function, and a `designateMaterials` function (and perhaps wrap these in an editor module.

I might start working on a PR in the next few days if I have time (I'm kinda new to Arma scripting so I may well need some help).

**Comment by ostinelli** [comment]
I am not sure that I get what you'd desired. Would you want workers to be spawned in map instead of being supplied by air?

BTW I'm undergoing a major refactoring so I wouldn't recommend working on a PR right now, let's talk first.

**Comment by Nels0** [comment]
I just made a start - I have a lot to learn...

Place down AI and Props in editor. 
Sync modules: Designate Supplies, and Designate workers.

Synchronise these modules to a UCM Logic module to add them to the module.

Synchronise Props/AI to appropriate modules, with some settings in each module, i.e

Designate Workers: 
 - Randomise Worker Uniform

Designate Supplies:
 - Weight
 - Finish position 
 - ETC

This means that there is:
 - Limited amount of workers/Supplies.
 - No in-game spawning.

**Comment by ostinelli** [comment]
Thank you for the suggestion @Nels0 but I don't see the point in this. You don't need this module to do that, you need to code a construction mod similar to Exile and other mods which have construction abilities to do what you intend to do. Nice idea, but outside the scope of this mod. Closing.
