### ISSUE TITLE
Make map markers optional

### ISSUE THREAD

**Issue by Pandexe** [ostinelli/SCAR_UCM#6]
Could be a nice feature for milsim groups to be able to choose wheter they want to see the markers or not.

**Comment by ostinelli** [comment]
Only a faction can see these markers, why would you like to hide them optionally? Trying to understand the scenario.

**Comment by Pandexe** [comment]
Well we play MilSim with out Any map markers. To force the leaders to
communicate over radio. So its more an immersion issue. But aften playing
with it a few missions. We think landing zone and construction zone is
okay. But we dont like we Canon follow the position of the workers on their
way to construction zone. Thats effective give everyone the position of the
team escorting Them. With out communication.

Hope thats make sende ☺️

Den 18. okt. 2017 10.17 AM skrev "Roberto Ostinelli" <
notifications@github.com>:

**Comment by ostinelli** [comment]
It does. Will think of adding this feature, thank you for the feedback.

**Comment by Pandexe** [comment]
You Are very welcome. Really Nice work and great idea you have with This
mod.

Den 18. okt. 2017 10.52 AM skrev "Roberto Ostinelli" <
notifications@github.com>:

**Comment by ostinelli** [comment]
This is now in. Thank you.

c357b44f9e70399ac91305766bca5a7b52a48f4d
